# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - implicit_return
  - weak_delegate
  - force_unwrapping
  - implicitly_unwrapped_optional
  
disabled_rules:
  - identifier_name
  - trailing_whitespace

# special configuration for rules
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 500
  error: 1000

function_parameter_count:
  warning: 10
  error: 20

large_tuple:
  warning: 2
  error: 3

line_length:
  warning: 220
  error: 400
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
