name: Jazzy publishing

on:
  push:
    branches: [ feature/jazzy ]

jobs:
  generate-docs:
    runs-on: macos-latest
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          xcodebuild-destination: 'platform=iOS Simulator,OS=14.0,name=iPhone 11'
          output: docs
      - uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
