name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to XCode 12
      run:  sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Generate XCode Project
      run:  swift package generate-xcodeproj
    - name: Run tests
      run:  xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' -scheme 'Formworks-Package'
